# Jekyll
markdown: redcarpet
permalink: /:categories/:title
pygments: true

baseurl: /cn

excerpt_separator: ""
comments: true


links:
  - title: About
    url: /cn/about/
  - title: Articles
    url: /cn/articles/
  - title: Blog
    url: /cn/
  - title: Category
    url: /cn/category/

# Personal
description: "Andy Lau / 刘松的博客"
ga_id: UA-49813880-1
name: Andy Lau
